# Сергей Лущик. 5 вариант.
## Лабораторная работа №1.
### Задача 1.

In [1]:
pairs = {"А":"Я","Б":"П","В":"Ф","Г":"К","Д":"Т",
         "Е":"Э","Ё":"О","Ж":"Ш","З":"С","И":"Ы","У":"Ю"}
pairs_r = {v: k for k, v in pairs.items()}
pairs.update(pairs_r)

my_name = 'Лущик Сергей Александрович'.upper()

my_wiered_name = ''
for letter in my_name:
    if letter in pairs:
        my_wiered_name += pairs[letter]
    else:
        my_wiered_name += letter
print(my_wiered_name)

ЛЮЩЫГ ЗЭРКЭЙ ЯЛЭГЗЯНТРЁФЫЧ


### Задача 2.

In [2]:
my_bday = [1996,2,21]
for f in bin, hex, oct:
    print("{}-{}-{}".format(f(my_bday[2]),f(my_bday[1]),f(my_bday[0])))

0b10101-0b10-0b11111001100
0x15-0x2-0x7cc
0o25-0o2-0o3714


## Лабораторная работа №2.

In [3]:
def season(month_number):
    if month_number > 2 and month_number < 6:
        return "Весна"
    elif month_number > 5 and month_number < 9:
        return "Лето"
    elif month_number > 8 and month_number < 12:
        return "Осень"
    elif month_number == 12 or month_number == 1 or month_number == 2:
        return "Зима"
    else:
        return "Номер месяца указан неверно"
    
for i in range(-1,14):
    print("{}\t{}".format(i,season(i)))

-1	Номер месяца указан неверно
0	Номер месяца указан неверно
1	Зима
2	Зима
3	Весна
4	Весна
5	Весна
6	Лето
7	Лето
8	Лето
9	Осень
10	Осень
11	Осень
12	Зима
13	Номер месяца указан неверно


## Лабораторная работа №3.

In [4]:
import time
def f(n):
    return 1./((2*n-1)**2)


for eps_pow in range(-6,-23,-1):
    
    eps = 10**eps_pow
    start_time = time.time()
    n, f_prev, f_curr, my_pi = 1, f(1), 0, 0
    while True:
        n += 1
        my_pi += f_prev
        f_curr = f(n)
        if (f_prev - f_curr <= eps): break
        f_prev = f_curr
        
    print("PI: {}\teps: 10^{}\tnum_iter: {}\nTIME: {}\n".format((my_pi*8)**.5, eps_pow, n, time.time() - start_time))

PI: 3.137611309036285	eps: 10^-6	num_iter: 81
TIME: 6.127357482910156e-05

PI: 3.139730645770133	eps: 10^-7	num_iter: 172
TIME: 0.00022292137145996094

PI: 3.1407299072358965	eps: 10^-8	num_iter: 370
TIME: 0.000453948974609375

PI: 3.1411917339975703	eps: 10^-9	num_iter: 795
TIME: 0.0009129047393798828

PI: 3.141406501947727	eps: 10^-10	num_iter: 1711
TIME: 0.0020389556884765625

PI: 3.1415062725150604	eps: 10^-11	num_iter: 3686
TIME: 0.0036859512329101562

PI: 3.141552553826981	eps: 10^-12	num_iter: 7939
TIME: 0.007323026657104492

PI: 3.141574038921428	eps: 10^-13	num_iter: 17101
TIME: 0.015573978424072266

PI: 3.141584013478969	eps: 10^-14	num_iter: 36842
TIME: 0.030627012252807617

PI: 3.1415886431818674	eps: 10^-15	num_iter: 79372
TIME: 0.06332683563232422

PI: 3.141590792106229	eps: 10^-16	num_iter: 170999
TIME: 0.14116191864013672

PI: 3.1415917895657794	eps: 10^-17	num_iter: 368405
TIME: 0.30693578720092773

PI: 3.14159225254476	eps: 10^-18	num_iter: 793702
TIME: 0.636934280395

## Лабораторная работа №4.

In [1]:
import numpy as np
def create_arr(n):
    X = np.random.rand(n)
    print("Массив случайных чисел:\n{}".format(X))
    X_max, X_min = np.max(X), np.min(X)
    print("X_max: {},\tX_min: {}".format(X_max, X_min))
    return  X / (X_max - X_min)

for i in [3,4,5]:
    print("Итоговый массив:\n{}\n\n".format(create_arr(i)))

Массив случайных чисел:
[0.34128669 0.39912499 0.55766573]
X_max: 0.557665726612,	X_min: 0.341286689037
Итоговый массив:
[1.57726318 1.84456401 2.57726318]


Массив случайных чисел:
[0.60637952 0.4473022  0.39504883 0.21669872]
X_max: 0.606379520975,	X_min: 0.216698720078
Итоговый массив:
[1.55609288 1.1478682  1.01377545 0.55609288]


Массив случайных чисел:
[0.48083564 0.76996101 0.91864741 0.17169952 0.3547187 ]
X_max: 0.918647412234,	X_min: 0.171699522686
Итоговый массив:
[0.64373385 1.03080954 1.22986814 0.22986814 0.47489082]


